// swift-tools-version: 5.10

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TravellerServer",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(
            name: "travellerserver",
            targets: ["TravellerServer"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", "4.99.3"..<"5.0.0"),
        .package(url: "https://github.com/apple/swift-nio.git", "2.65.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "TravellerServer",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio")
            ],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
